/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAiInsightsRouteImport } from './routes/_shell/ai-insights'
import { Route as ShellLeaksRouteImport } from './routes/_shell/leaks'
import { Route as ShellTransactionsRouteImport } from './routes/_shell/transactions'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiInsightsRoute = ShellAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaksRoute = ShellLeaksRouteImport.update({
  id: '/leaks',
  path: '/leaks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/ai-insights': typeof ShellAiInsightsRoute
  '/leaks': typeof ShellLeaksRoute
  '/transactions': typeof ShellTransactionsRoute
}
export interface FileRoutesByTo {
  '/ai-insights': typeof ShellAiInsightsRoute
  '/leaks': typeof ShellLeaksRoute
  '/transactions': typeof ShellTransactionsRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/ai-insights': typeof ShellAiInsightsRoute
  '/_shell/leaks': typeof ShellLeaksRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-insights' | '/leaks' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/ai-insights' | '/leaks' | '/transactions' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/ai-insights'
    | '/_shell/leaks'
    | '/_shell/transactions'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai-insights': {
      id: '/_shell/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof ShellAiInsightsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leaks': {
      id: '/_shell/leaks'
      path: '/leaks'
      fullPath: '/leaks'
      preLoaderRoute: typeof ShellLeaksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAiInsightsRoute: typeof ShellAiInsightsRoute
  ShellLeaksRoute: typeof ShellLeaksRoute
  ShellTransactionsRoute: typeof ShellTransactionsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAiInsightsRoute: ShellAiInsightsRoute,
  ShellLeaksRoute: ShellLeaksRoute,
  ShellTransactionsRoute: ShellTransactionsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
